const express = require("express");
const cors = require("cors");
const app = express();
const port = 8000;
app.use(cors({origin: "http://localhost:3000"}));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
require('./config/mongoose.config'); 
require('./routes/manager.routes') (app);
app.listen(port, () => console.log(`backend server is up on port: ${port}`));